### PR TITLE
refactor user service

### PR DESCRIPTION
**Pull request by kunwar97**

### CODE REVIEW

**Comment by tgiardina** [comment]
@kunwar97 Dang! You resolved #20, but I think there's a problem with the issue itself! I forgot that these endpoints need to generate and return a token, and generating a token is neither the job of a controller nor of a repository, so it must be the job of a separate service layer. Does that make sense? I'll update the issue ASAP.

Meanwhile, there are still some good changes I would like to merge from this PR. In particular,

1. Deleting the `result` helper is still good.
2. Swtiching `src/controllers/user` from using `result` to using a `try-catch` block is good.

If you copy back all of `src/services/user` and also switch it from using `result` to throwing errors, then I should be able to merge this ASAP and close #21.

**Comment by kunwar97** [comment]
@tgiardina sure

**Comment by tgiardina** [comment]
I'm trying to refactor things so that I don't need `UserService`. Let's put this on hold until I figure that out.

**Comment by tgiardina** [comment]
Pushed this through. Thanks @kunwar97!

**Pull request merged**
